# Generated by Django 2.1.2 on 2018-11-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='ABC', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.CharField(default='ABC', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='ABC', max_length=30),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='ABC', max_length=30),
        ),
    ]
